#!/bin/bash
#watch -c -n 3600 lxc exec kvm0:mail su gmason ~/agenda.sh | cat
mystart=$(date --date='TZ="America/Detroit" today 00:00' +%Y-%m-%dT%H:%M%z)
myend=$(date --date='TZ="America/Detroit" 1 month 23:59' +%Y-%m-%dT%H:%M%z)
width=$(expr `tput cols` - 20)
lxc exec kvm0:mail -- su gmason -c "gcalcli agenda $mystart $myend --detail_url long --detail_email --detail_length --detail_calendar --detail_description --detail_attendees --detail_description_width $width --military"

