#!/bin/bash
# EOD automation for nodoubleg.
# No need for markdown notes, as my notes on are *paper* !
# So, we're just doing all this shit in bash, because https://www.youtube.com/watch?v=Qy-Y3HJNU_s
#rcpt='whiskey-reports@greenteam.canonical.com'
#rcpt='tango-reports@greenteam.canonical.com'
rcpt='foxtrot-reports@greenteam.canonical.com'

if [ "$1" == "pvg" ]
then
    vg="pvg" 
elif [ "$1" == "bvg" ]
then
    vg="bvg"
elif [ "$1" == "wvg" ]
then
    vg="wvg"
else
    echo "Usage: $0 <pvg|wvg|bvg>"
    exit 1
fi


myname=$(getent passwd $LOGNAME | cut -d: -f5 | cut -d, -f1)
subject="`date '+%Y-%m-%d (%A)'` EOD Report for $myname"
#TODO: fix this to not need a temp file
tmpfile=/tmp/eod-$$-tmpfile

# first, let's fetch some victory! 
# due to UTF8, these lines may not display properly in an editor.
getvictory() {
w3m https://portal.admin.canonical.com/fail -dump | head -n1 | grep -qi victory
}
if getvictory
then
  victory='😄 💪🐸' 
else
  echo 'FAIL! Fix this fail:'
  w3m https://portal.admin.canonical.com/fail -dump
  w3m https://portal.admin.canonical.com/fail -dump_source | gunzip -c | awk -F '"' '/target="_blank">[C,U]/{print $2}'
  exit 1
fi  

# Let's scrape some stuff out of myday.
myday=$(w3m https://portal.admin.canonical.com/myday -dump_source | gunzip -c)

# Just defining template stuff here, because why not.
SOD_MISC_INTERRUPTS='SOD/Misc stuff:
===============
 - 
 
Maintenance time:
=================
 -  
 
Humans/PD/interruptions:
========================'

ALERTHEADER='PD Alerts:
=========='

TICKETHEADER='
 
Tickets:
========'
PVG="
EOD Checklist:
 - PVG 
   - Incoming RT queue: 
   - Nagios/Maintenance Work: 
 - Portal Fail Page: ${victory}
 - RQ items: "
WVG="
EOD Checklist:
 - WVG 
   - Incoming RT queue: 
   - Nagios/Maintenance Work: 
 - Portal Fail Page: ${victory}
 - RQ items: "
BVG="
EOD Checklist:
 - BVG 
   - Incoming RT queue: n/a
   - Nagios/Maintenance Work: 
 - Portal Fail Page: ${victory}
 - RQ items: "

# Assemble the body.
echo "$SOD_MISC_INTERRUPTS" >> $tmpfile
# Fetching list of mentions in IRC from bouncer.
ssh gmason@bip.nodoubleg.com 'sudo -u bip bash /home/bip/todays_mentions.sh' >> $tmpfile
# get today's PD alerts.
echo "$ALERTHEADER" >> $tmpfile
ssh gmason@bip.nodoubleg.com 'sudo -u bip bash /home/bip/todays_alerts.sh' >> $tmpfile
echo "$TICKETHEADER" >> $tmpfile
# get list of all ticket titles.
echo "$myday" | grep 'href="https://rt' | awk -F '<|>' '{print $5}' >> $tmpfile
#TODO: add logic by fetching {W,P,B}VG status from Dashboard.
echo ''
if [ "$vg" == "pvg" ]
then
	echo "$PVG" >> $tmpfile
elif [ "$vg" == "wvg" ]
then
	echo "$WVG" >> $tmpfile
elif [ "$vg" == "bvg" ]
then
	echo "$BVG" >> $tmpfile
fi
echo "$myday" | grep 'Work time logged in RT' -A4 >> $tmpfile

# Email time! finally! woo!
#kmail -s "$subject" --body "`cat $tmpfile`" $rcpt
cat $tmpfile | xsel -i --clipboard
echo
echo "body is just in clipboard. get a better email client!"
echo 
sylpheed --compose $rcpt "mailto:$rcpt?subject=$subject"



# Cleanup
rm $tmpfile

notify-send --urgency=CRITICAL -t 3600000 "DROP TOPICS!"
