#!/bin/bash
apt upgrade > /dev/null 2>&1
apt dist-upgrade -y > /dev/null 2>&1
# TODO: add logic to throw warning when reboot is necessary from recent update
# zenity --width=700 --height=400 --warning --title='Reboot necessary' --text='<span size="75000">Reboot required!\n\n</span><span size="x-large">Reboot necessary for recent update</span>'  
